spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
      additional-pahts: src/main/java
  profiles:
    active: dev

logging:
  level:
    root: warn
    com.zhoushiya.bootlaunch: trace
  pattern:
    console: '自定义日志:%p%m%n'